import {StyleSheet} from 'react-native';

export const Mystyles = StyleSheet.create({
  page: {
    fontFamily: 'Arial',
    flex: 1,
    margin: 20,
    marginLeft: 30,
    marginRight: 30,
  },
  bg: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    width: null,
    height: null,
  },
  head: {
    fontFamily: 'Arial',
    fontSize: 23,
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 15,
    marginTop: 10,
  },
  header: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headertext: {
    color: '#FFFFFF',
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fontSize: 20,
    paddingLeft: 10,
  },
  inputcontainer: {
    flex: 1,
    justifyContent: 'center',
  },
  input: {
    borderRadius: 0,
    marginTop: 12,
    justifyContent: 'center',
    borderBottomColor: '#FFFFFF',
    borderBottomWidth: 2,
    // backgroundColor: 'rgba(136, 14, 79, 0.3)',
    color: '#ffffff',
    fontFamily: 'Arial',
    padding: 12,
    paddingLeft: 18,
    fontSize: 15,
  },
  buttoncontainer: {
    borderRadius: 25,
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#c21f77',
    marginTop: 50,
    padding: 12,
    width: '40%',
  },
  homebutton: {
    borderRadius: 25,
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#388E3C',
    marginTop: 50,
    padding: 12,
    width: '40%',
  },
  buttontext: {
    textAlign: 'center',
    color: '#ffffff',
    fontFamily: 'Arial',
    fontSize: 17,
    fontWeight: 'bold',
  },
  confirmPage: {
    flex: 1,
    backgroundColor: '#181818',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmText: {
    color: '#388E3C',
    fontFamily: 'Arial',
    fontSize: 25,
  },
});
